version: '2'
services:
  php:
    build:
      context: .
      dockerfile: PHPService/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - ./PHPService/:/var/www/html/
    env_file:
      - db_param_product.env


  flask-api:
    image: reporter/flask-api
    container_name: flask-api
    build:
      context: .
      target: debug
      dockerfile: PythonService/Dockerfile
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - ./PythonService/:/app
    environment:
      - FLASK_DEBUG=1
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app", "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge
